// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: docs/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryAck_Status int32

const (
	DeliveryAck_STATUS_ACK  DeliveryAck_Status = 0
	DeliveryAck_STATUS_NACK DeliveryAck_Status = 1
)

// Enum value maps for DeliveryAck_Status.
var (
	DeliveryAck_Status_name = map[int32]string{
		0: "STATUS_ACK",
		1: "STATUS_NACK",
	}
	DeliveryAck_Status_value = map[string]int32{
		"STATUS_ACK":  0,
		"STATUS_NACK": 1,
	}
)

func (x DeliveryAck_Status) Enum() *DeliveryAck_Status {
	p := new(DeliveryAck_Status)
	*p = x
	return p
}

func (x DeliveryAck_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryAck_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_docs_protocol_proto_enumTypes[0].Descriptor()
}

func (DeliveryAck_Status) Type() protoreflect.EnumType {
	return &file_docs_protocol_proto_enumTypes[0]
}

func (x DeliveryAck_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryAck_Status.Descriptor instead.
func (DeliveryAck_Status) EnumDescriptor() ([]byte, []int) {
	return file_docs_protocol_proto_rawDescGZIP(), []int{3, 0}
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ServerMessage:
	//
	//	*ServerMessage_PushNotification
	ServerMessage isServerMessage_ServerMessage `protobuf_oneof:"server_message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_docs_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_docs_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_docs_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetServerMessage() isServerMessage_ServerMessage {
	if x != nil {
		return x.ServerMessage
	}
	return nil
}

func (x *ServerMessage) GetPushNotification() *PushNotification {
	if x != nil {
		if x, ok := x.ServerMessage.(*ServerMessage_PushNotification); ok {
			return x.PushNotification
		}
	}
	return nil
}

type isServerMessage_ServerMessage interface {
	isServerMessage_ServerMessage()
}

type ServerMessage_PushNotification struct {
	PushNotification *PushNotification `protobuf:"bytes,1,opt,name=push_notification,json=pushNotification,proto3,oneof"`
}

func (*ServerMessage_PushNotification) isServerMessage_ServerMessage() {}

type PushNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // uuid format
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // rfc 3339 format
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNotification) Reset() {
	*x = PushNotification{}
	mi := &file_docs_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotification) ProtoMessage() {}

func (x *PushNotification) ProtoReflect() protoreflect.Message {
	mi := &file_docs_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotification.ProtoReflect.Descriptor instead.
func (*PushNotification) Descriptor() ([]byte, []int) {
	return file_docs_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *PushNotification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PushNotification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PushNotification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PushNotification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ClientMessage:
	//
	//	*ClientMessage_DeliveryAck
	ClientMessage isClientMessage_ClientMessage `protobuf_oneof:"client_message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_docs_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_docs_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_docs_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMessage) GetClientMessage() isClientMessage_ClientMessage {
	if x != nil {
		return x.ClientMessage
	}
	return nil
}

func (x *ClientMessage) GetDeliveryAck() *DeliveryAck {
	if x != nil {
		if x, ok := x.ClientMessage.(*ClientMessage_DeliveryAck); ok {
			return x.DeliveryAck
		}
	}
	return nil
}

type isClientMessage_ClientMessage interface {
	isClientMessage_ClientMessage()
}

type ClientMessage_DeliveryAck struct {
	DeliveryAck *DeliveryAck `protobuf:"bytes,1,opt,name=delivery_ack,json=deliveryAck,proto3,oneof"`
}

func (*ClientMessage_DeliveryAck) isClientMessage_ClientMessage() {}

type DeliveryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PushId        string                 `protobuf:"bytes,1,opt,name=push_id,json=pushId,proto3" json:"push_id,omitempty"`
	Status        DeliveryAck_Status     `protobuf:"varint,2,opt,name=status,proto3,enum=protocol.DeliveryAck_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAck) Reset() {
	*x = DeliveryAck{}
	mi := &file_docs_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAck) ProtoMessage() {}

func (x *DeliveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_docs_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAck.ProtoReflect.Descriptor instead.
func (*DeliveryAck) Descriptor() ([]byte, []int) {
	return file_docs_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryAck) GetPushId() string {
	if x != nil {
		return x.PushId
	}
	return ""
}

func (x *DeliveryAck) GetStatus() DeliveryAck_Status {
	if x != nil {
		return x.Status
	}
	return DeliveryAck_STATUS_ACK
}

var File_docs_protocol_proto protoreflect.FileDescriptor

const file_docs_protocol_proto_rawDesc = "" +
	"\n" +
	"\x13docs/protocol.proto\x12\bprotocol\"l\n" +
	"\rServerMessage\x12I\n" +
	"\x11push_notification\x18\x01 \x01(\v2\x1a.protocol.PushNotificationH\x00R\x10pushNotificationB\x10\n" +
	"\x0eserver_message\"k\n" +
	"\x10PushNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\"]\n" +
	"\rClientMessage\x12:\n" +
	"\fdelivery_ack\x18\x01 \x01(\v2\x15.protocol.DeliveryAckH\x00R\vdeliveryAckB\x10\n" +
	"\x0eclient_message\"\x87\x01\n" +
	"\vDeliveryAck\x12\x17\n" +
	"\apush_id\x18\x01 \x01(\tR\x06pushId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.protocol.DeliveryAck.StatusR\x06status\")\n" +
	"\x06Status\x12\x0e\n" +
	"\n" +
	"STATUS_ACK\x10\x00\x12\x0f\n" +
	"\vSTATUS_NACK\x10\x01B\vZ\t/protocolb\x06proto3"

var (
	file_docs_protocol_proto_rawDescOnce sync.Once
	file_docs_protocol_proto_rawDescData []byte
)

func file_docs_protocol_proto_rawDescGZIP() []byte {
	file_docs_protocol_proto_rawDescOnce.Do(func() {
		file_docs_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_protocol_proto_rawDesc), len(file_docs_protocol_proto_rawDesc)))
	})
	return file_docs_protocol_proto_rawDescData
}

var file_docs_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_docs_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_docs_protocol_proto_goTypes = []any{
	(DeliveryAck_Status)(0),  // 0: protocol.DeliveryAck.Status
	(*ServerMessage)(nil),    // 1: protocol.ServerMessage
	(*PushNotification)(nil), // 2: protocol.PushNotification
	(*ClientMessage)(nil),    // 3: protocol.ClientMessage
	(*DeliveryAck)(nil),      // 4: protocol.DeliveryAck
}
var file_docs_protocol_proto_depIdxs = []int32{
	2, // 0: protocol.ServerMessage.push_notification:type_name -> protocol.PushNotification
	4, // 1: protocol.ClientMessage.delivery_ack:type_name -> protocol.DeliveryAck
	0, // 2: protocol.DeliveryAck.status:type_name -> protocol.DeliveryAck.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_docs_protocol_proto_init() }
func file_docs_protocol_proto_init() {
	if File_docs_protocol_proto != nil {
		return
	}
	file_docs_protocol_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerMessage_PushNotification)(nil),
	}
	file_docs_protocol_proto_msgTypes[2].OneofWrappers = []any{
		(*ClientMessage_DeliveryAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_protocol_proto_rawDesc), len(file_docs_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_docs_protocol_proto_goTypes,
		DependencyIndexes: file_docs_protocol_proto_depIdxs,
		EnumInfos:         file_docs_protocol_proto_enumTypes,
		MessageInfos:      file_docs_protocol_proto_msgTypes,
	}.Build()
	File_docs_protocol_proto = out.File
	file_docs_protocol_proto_goTypes = nil
	file_docs_protocol_proto_depIdxs = nil
}
