// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: docs/verifier.proto

package verifier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyTokenResponse_Status int32

const (
	VerifyTokenResponse_STATUS_OK                    VerifyTokenResponse_Status = 0
	VerifyTokenResponse_STATUS_DEVICE_NOT_FOUND      VerifyTokenResponse_Status = 1
	VerifyTokenResponse_STATUS_BAD_TOKEN             VerifyTokenResponse_Status = 2 // token cannot be parsed or signed with incorrect secret
	VerifyTokenResponse_STATUS_TOKEN_EXPIRED         VerifyTokenResponse_Status = 3
	VerifyTokenResponse_STATUS_INTERNAL_SERVER_ERROR VerifyTokenResponse_Status = 4
)

// Enum value maps for VerifyTokenResponse_Status.
var (
	VerifyTokenResponse_Status_name = map[int32]string{
		0: "STATUS_OK",
		1: "STATUS_DEVICE_NOT_FOUND",
		2: "STATUS_BAD_TOKEN",
		3: "STATUS_TOKEN_EXPIRED",
		4: "STATUS_INTERNAL_SERVER_ERROR",
	}
	VerifyTokenResponse_Status_value = map[string]int32{
		"STATUS_OK":                    0,
		"STATUS_DEVICE_NOT_FOUND":      1,
		"STATUS_BAD_TOKEN":             2,
		"STATUS_TOKEN_EXPIRED":         3,
		"STATUS_INTERNAL_SERVER_ERROR": 4,
	}
)

func (x VerifyTokenResponse_Status) Enum() *VerifyTokenResponse_Status {
	p := new(VerifyTokenResponse_Status)
	*p = x
	return p
}

func (x VerifyTokenResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerifyTokenResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_docs_verifier_proto_enumTypes[0].Descriptor()
}

func (VerifyTokenResponse_Status) Type() protoreflect.EnumType {
	return &file_docs_verifier_proto_enumTypes[0]
}

func (x VerifyTokenResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerifyTokenResponse_Status.Descriptor instead.
func (VerifyTokenResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_docs_verifier_proto_rawDescGZIP(), []int{1, 0}
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_docs_verifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_verifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_docs_verifier_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	DeviceId      string                     `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        VerifyTokenResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=verifier.VerifyTokenResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_docs_verifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_verifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_docs_verifier_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyTokenResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *VerifyTokenResponse) GetStatus() VerifyTokenResponse_Status {
	if x != nil {
		return x.Status
	}
	return VerifyTokenResponse_STATUS_OK
}

var File_docs_verifier_proto protoreflect.FileDescriptor

const file_docs_verifier_proto_rawDesc = "" +
	"\n" +
	"\x13docs/verifier.proto\x12\bverifier\"*\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xf9\x01\n" +
	"\x13VerifyTokenResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.verifier.VerifyTokenResponse.StatusR\x06status\"\x86\x01\n" +
	"\x06Status\x12\r\n" +
	"\tSTATUS_OK\x10\x00\x12\x1b\n" +
	"\x17STATUS_DEVICE_NOT_FOUND\x10\x01\x12\x14\n" +
	"\x10STATUS_BAD_TOKEN\x10\x02\x12\x18\n" +
	"\x14STATUS_TOKEN_EXPIRED\x10\x03\x12 \n" +
	"\x1cSTATUS_INTERNAL_SERVER_ERROR\x10\x042V\n" +
	"\bVerifier\x12J\n" +
	"\vVerifyToken\x12\x1c.verifier.VerifyTokenRequest\x1a\x1d.verifier.VerifyTokenResponseB\vZ\t/verifierb\x06proto3"

var (
	file_docs_verifier_proto_rawDescOnce sync.Once
	file_docs_verifier_proto_rawDescData []byte
)

func file_docs_verifier_proto_rawDescGZIP() []byte {
	file_docs_verifier_proto_rawDescOnce.Do(func() {
		file_docs_verifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_verifier_proto_rawDesc), len(file_docs_verifier_proto_rawDesc)))
	})
	return file_docs_verifier_proto_rawDescData
}

var file_docs_verifier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_docs_verifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_docs_verifier_proto_goTypes = []any{
	(VerifyTokenResponse_Status)(0), // 0: verifier.VerifyTokenResponse.Status
	(*VerifyTokenRequest)(nil),      // 1: verifier.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),     // 2: verifier.VerifyTokenResponse
}
var file_docs_verifier_proto_depIdxs = []int32{
	0, // 0: verifier.VerifyTokenResponse.status:type_name -> verifier.VerifyTokenResponse.Status
	1, // 1: verifier.Verifier.VerifyToken:input_type -> verifier.VerifyTokenRequest
	2, // 2: verifier.Verifier.VerifyToken:output_type -> verifier.VerifyTokenResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_docs_verifier_proto_init() }
func file_docs_verifier_proto_init() {
	if File_docs_verifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_verifier_proto_rawDesc), len(file_docs_verifier_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_verifier_proto_goTypes,
		DependencyIndexes: file_docs_verifier_proto_depIdxs,
		EnumInfos:         file_docs_verifier_proto_enumTypes,
		MessageInfos:      file_docs_verifier_proto_msgTypes,
	}.Build()
	File_docs_verifier_proto = out.File
	file_docs_verifier_proto_goTypes = nil
	file_docs_verifier_proto_depIdxs = nil
}
